import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthProvider";
import Navbar from "./components/navbarComponents/Navbar";
import SidebarMenu from "./components/SidebarComponents/sidebarnew";
import Loading from "./loading";
import moment from "moment";
import LayoutClient from "./LayoutClient";

const inter = Inter({ subsets: ["latin"] });

const currentYear = moment().year();

export const metadata: Metadata = {
  title: "Devonix",
  description: "Generated by Varsil Suvagiya",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex-1 overflow-x-hidden overflow-y-auto">
          <LayoutClient>{children}</LayoutClient>

        </main>
      </body>
    </html>
  );
}
